language: perl
perl:
  - "5.22"
cache:
  apt: true
  directories:
    - /home/travis/perl5/perlbrew/perls/5.22.0
sudo: false
before_install:
  - cpanm --quiet --notest --skip-satisfied Perl::Critic
  - perlcritic --quiet --single-policy=RequireTidyCode --statistics .
install:
  - dzil authordeps --missing | cpanm --quiet --notest --skip-satisfied
  - dzil listdeps --missing | cpanm --quiet --notest --skip-satisfied
  - cpanm --quiet --notest --skip-satisfied DBI IPC::Shareable Parallel::ForkManager Digest::HMAC_SHA1 String::Escape XML::LibXML Net::SFTP::Foreign
script: prove --timer --lib --recurse --jobs 2 --shuffle t/ 
