language: perl
perl:
  - "5.22"
cache:
  apt: true
  directories:
    - /home/travis/perl5/perlbrew/perls/5.22.0
sudo: false
before_install:
  - cpanm --quiet --notest Perl::Critic
  - perlcritic --quiet --single-policy=RequireTidyCode bin
install:
  - dzil authordeps --missing | cpanm --quiet --notest
  - dzil listdeps --missing | cpanm --quiet --notest
  - cpanm --quiet --notest DBI IPC::Shareable Parallel::ForkManager Digest::HMAC_SHA1 String::Escape XML::LibXML Net::SFTP::Foreign IO::Pty
script:
  - dzil build --in build --notgz
  - cd build && prove --timer --lib --recurse --jobs 2 --shuffle t/
