dist: bionic
os: linux
language: perl
perl:
  - "5.30"
jobs:
  include:
    - stage: test
      env:
        - AUTHOR_TESTING=1 RELEASE_TESTING=1 PERL_CPANM_OPT="--quiet --notest"
      cache:
        directories:
          - ${PERLBREW_ROOT}/perls/${PERLBREW_PERL}/lib
          - ${PERLBREW_ROOT}/perls/${PERLBREW_PERL}/bin
      addons:
        apt:
          packages:
            - libmagic-dev
      before_install:
        - cpanm Perl::Critic Perl::Tidy
        - mkdir ~/.dzil
        - export AUTHOR_EMAIL="$(git log -1 ${TRAVIS_COMMIT} --pretty='%aE')"
        - export AUTHOR_NAME="$(git log -1 ${TRAVIS_COMMIT} --pretty='%aN')"
        - echo -e "[%User]\nname = ${AUTHOR_EMAIL}\nemail = ${AUTHOR_EMAIL}\n" > ~/.dzil/config.ini
        - dzil authordeps | cpanm
        - dzil listdeps --author | cpanm
        # installing OS-specific dependencies
        - cpanm IO::Pty Net::SFTP::Foreign
        # installing optional dependencies
        - cpanm DBI IPC::Shareable XML::LibXML Expect
        - cpanm File::LibMagic Test::mysqld
        - cpanm Devel::Cover::Report::Coveralls
      install:
        - dzil build --in build --notgz
      script:
        - cd build
        - HARNESS_PERL_SWITCHES=-MDevel::Cover=+ignore,^t/ prove --timer --lib --recurse --jobs $(nproc) --shuffle t/
        - prove --timer --lib --recurse --jobs $(nproc) --shuffle xt/
      after_success:
        - cover -report coveralls
    - stage: test
      os: windows
      language: shell
      env:
        - PERL_CPANM_OPT="--quiet --notest"
      cache:
        directories:
          - /c/Strawberry
      before_install:
        - cinst -y strawberryperl
        - export "PATH=/c/Strawberry/perl/site/bin:/c/Strawberry/perl/bin:/c/Strawberry/c/bin:$PATH"
        - export "PERL5LIB=/c/Strawberry/perl/site/lib:/c/Strawberry/perl/site/lib:/c/Strawberry/perl/vendor/lib:/c/Strawberry/perl/lib"
        - ln -snf /c/Strawberry/perl/bin/perl /bin/perl
        - cpanm --reinstall Module::Pluggable::Object
        - cpanm Dist::Zilla
        - mkdir ~/.dzil
        - export AUTHOR_EMAIL="$(git log -1 ${TRAVIS_COMMIT} --pretty='%aE')"
        - export AUTHOR_NAME="$(git log -1 ${TRAVIS_COMMIT} --pretty='%aN')"
        - echo -e "[%User]\nname = ${AUTHOR_EMAIL}\nemail = ${AUTHOR_EMAIL}\n" > ~/.dzil/config.ini
        - dzil authordeps | cpanm
        - dzil listdeps --author | cpanm
        # installing OS-specific dependencies
        - cpanm Net::SSH2
        # installing optional dependencies
        - cpanm DBI XML::LibXML
        - cpanm --reinstall App::Prove
      install:
        - dzil build --in build --notgz
      script:
        - cd build
        - prove --timer --lib --recurse --jobs $(nproc) --shuffle t/
    - stage: test
      os: osx
      osx_image: xcode11.2
      language: shell
      env:
        - PERL_CPANM_OPT="--quiet --notest"
      cache:
        directories:
          - /usr/local/Cellar/perl
      addons:
        homebrew:
          packages:
            - perl
            - cpanminus
          update: true
      before_install:
        - export PERL_VERSION="$(brew list --versions perl | cut -d' ' -f 2)"
        - export "PATH=/usr/local/Cellar/perl/${PERL_VERSION}/bin:${PATH}"
        - cpanm Dist::Zilla
        - mkdir ~/.dzil
        - export AUTHOR_EMAIL="$(git log -1 ${TRAVIS_COMMIT} --pretty='%aE')"
        - export AUTHOR_NAME="$(git log -1 ${TRAVIS_COMMIT} --pretty='%aN')"
        - echo -e "[%User]\nname = ${AUTHOR_EMAIL}\nemail = ${AUTHOR_EMAIL}\n" > ~/.dzil/config.ini
        - dzil authordeps | cpanm
        - dzil listdeps --author | cpanm
        # installing OS-specific dependencies
        - cpanm IO::Pty Net::SFTP::Foreign
        # installing optional dependencies
        - cpanm DBI IPC::Shareable XML::LibXML Expect
      install:
        - dzil build --in build --notgz
      script:
        - cd build
        - prove --timer --lib --recurse --jobs $(sysctl -n hw.ncpu) --shuffle t/
